/**
 * Generated by scripts/generate-redirects.js — do not hand-edit.
 * Edge-safe route data for functions/[[path]].js.
 */
export const CANONICAL_ROUTES = [
  "/",
  "/public-record/",
  "/reading-room/",
  "/evidence-trajectories/",
  "/events/",
  "/programmes/",
  "/methodology/",
  "/welcome/",
  "/about/",
  "/about/origins/",
  "/notes/",
  "/how-to-read/",
  "/guides/",
  "/guides/how-to-read/",
  "/guides/mcp-access/",
  "/institutional-health/",
  "/institutional-changelog/",
  "/tokens/",
  "/programmes/prog-qe/",
  "/programmes/prog-ai/",
  "/programmes/prog-am/",
  "/programmes/prog-bt/",
  "/notes/fm-001/",
  "/notes/en-001/",
  "/notes/aud-001/",
  "/notes/pn-ai-001/",
  "/notes/pn-qe-001/",
  "/notes/le-ai-001/",
  "/notes/le-qe-001/"
];
export const LEGACY_REDIRECTS = [
  {
    "from": "/programmes/prog-mf",
    "to": "/programmes/prog-am/"
  },
  {
    "from": "/programmes/prog-mf/",
    "to": "/programmes/prog-am/"
  }
];
