/**
 * generate-sitemap.js — writes a sitemap index and three focused child
 * sitemaps from the canonical corpus and route data.
 *
 * Generated on every production build. Do not hand-edit the XML outputs.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createServer } from "vite";
import { getIndexableRouteGroups } from "./route-manifest.js";

const ROOT = path.dirname(fileURLToPath(import.meta.url)).replace(/scripts$/, "");
const PUBLIC_DIR = path.join(ROOT, "public");
const BASE_URL = "https://faultlinewatch.com";
const EVIDENCE_ENTRY_FIELD = /^(?:instance|instances|evidence)_(?:logged|appended)$/i;
const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/;

function fail(message) {
  throw new Error(`Sitemap generation failed: ${message}`);
}

function absoluteUrl(route) {
  return `${BASE_URL}${route}`;
}

function assertIsoDate(date, recordId) {
  if (!ISO_DATE.test(date)) {
    fail(`${recordId} has a non-ISO evidence entry date: ${date}`);
  }
  const parsed = new Date(`${date}T00:00:00Z`);
  if (Number.isNaN(parsed.getTime()) || parsed.toISOString().slice(0, 10) !== date) {
    fail(`${recordId} has an invalid evidence entry date: ${date}`);
  }
}

export function getLastEvidenceEntryDate(record) {
  const evidenceEntries = (record.mutationLog || []).filter((entry) =>
    EVIDENCE_ENTRY_FIELD.test(entry.field)
  );
  if (evidenceEntries.length === 0) {
    fail(`${record.id} has no governed evidence-entry mutation`);
  }

  for (const entry of evidenceEntries) assertIsoDate(entry.date, record.id);
  return evidenceEntries.map((entry) => entry.date).sort().at(-1);
}

function buildUrlset(entries) {
  const urls = entries
    .map(({ route, lastmod }) =>
      [
        "  <url>",
        `    <loc>${absoluteUrl(route)}</loc>`,
        ...(lastmod ? [`    <lastmod>${lastmod}</lastmod>`] : []),
        "  </url>",
      ].join("\n")
    )
    .join("\n");

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Generated by scripts/generate-sitemap.js — do not hand-edit. -->",
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    urls,
    "</urlset>",
    "",
  ].join("\n");
}

function buildIndex(filenames) {
  const sitemaps = filenames
    .map((filename) =>
      [
        "  <sitemap>",
        `    <loc>${BASE_URL}/${filename}</loc>`,
        "  </sitemap>",
      ].join("\n")
    )
    .join("\n");

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Generated by scripts/generate-sitemap.js — do not hand-edit. -->",
    '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    sitemaps,
    "</sitemapindex>",
    "",
  ].join("\n");
}

const server = await createServer({
  root: ROOT,
  server: { middlewareMode: true },
  appType: "custom",
  logLevel: "silent",
});

let records;
try {
  ({ ALL_RECORDS: records } = await server.ssrLoadModule("/src/data/corpus.js"));
} finally {
  await server.close();
}

const indexable = await getIndexableRouteGroups();

const sitemapFiles = {
  "sitemap-records.xml": buildUrlset(
    records.map((record) => ({
      route: `/the-record/${record.id.toLowerCase()}/`,
      lastmod: getLastEvidenceEntryDate(record),
    }))
  ),
  "sitemap-notes.xml": buildUrlset(
    indexable.notes.map((route) => ({ route }))
  ),
  "sitemap-pages.xml": buildUrlset(indexable.pages.map((route) => ({ route }))),
};

if (records.length === 0) fail("resolved zero Frontier Records");
if (indexable.notes.length === 0) fail("resolved zero indexable notes");

fs.mkdirSync(PUBLIC_DIR, { recursive: true });
for (const [filename, contents] of Object.entries(sitemapFiles)) {
  fs.writeFileSync(path.join(PUBLIC_DIR, filename), contents, "utf8");
}
fs.writeFileSync(
  path.join(PUBLIC_DIR, "sitemap.xml"),
  buildIndex(Object.keys(sitemapFiles)),
  "utf8"
);

console.log(
  `Sitemap index generated (${records.length} records, ${indexable.notes.length} notes, ${indexable.pages.length} pages) -> public/sitemap.xml`
);
