/**
 * generate-sitemap.js — writes public/sitemap.xml from the canonical
 * route manifest (scripts/route-manifest.js), the same source of truth
 * generate-redirects.js and scripts/smoke-live.js read from.
 *
 * Replaces the previous hand-maintained sitemap.xml, which drifted from
 * reality (missing /events/, /institutional-changelog/) the same way the
 * old hand-maintained _redirects drifted into a soft-404 producer — one
 * manifest, regenerated on every build, is the fix for both.
 *
 * Runs as part of `npm run build` (prebuild), alongside generate:redirects.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { getSitemapRoutes } from "./route-manifest.js";

const ROOT = path.dirname(fileURLToPath(import.meta.url)).replace(/scripts$/, "");
const OUT_PATH = path.join(ROOT, "public", "sitemap.xml");
const BASE_URL = "https://faultlinewatch.com";

function fail(message) {
  console.error(`Sitemap generation failed: ${message}`);
  process.exitCode = 1;
}

// Priority/changefreq by route pattern, matching the values the previous
// hand-maintained sitemap used for routes it already listed.
function sitemapMeta(route) {
  if (route === "/") return { changefreq: "weekly", priority: "1.0" };
  if (route === "/the-record/") return { changefreq: "weekly", priority: "0.9" };
  if (route === "/evidence-trajectories/" || route === "/events/") {
    return { changefreq: "weekly", priority: "0.7" };
  }
  if (route === "/institutional-changelog/") return { changefreq: "weekly", priority: "0.5" };
  if (/^\/the-record\/[a-z0-9-]+\/$/.test(route)) return { changefreq: "monthly", priority: "0.8" };
  if (route.startsWith("/events/")) return { changefreq: "monthly", priority: "0.6" };
  if (route === "/programmes/" || route === "/notes/") return { changefreq: "monthly", priority: "0.7" };
  if (route.startsWith("/programmes/") || route.startsWith("/notes/")) {
    return { changefreq: "monthly", priority: "0.6" };
  }
  if (route === "/welcome/") return { changefreq: "monthly", priority: "0.6" };
  if (route === "/methodology/" || route === "/about/" || route === "/guides/how-to-read/") {
    return { changefreq: "monthly", priority: "0.5" };
  }
  return { changefreq: "monthly", priority: "0.4" };
}

function buildSitemap(routes) {
  const urls = routes
    .map((route) => {
      const { changefreq, priority } = sitemapMeta(route);
      return [
        "  <url>",
        `    <loc>${BASE_URL}${route}</loc>`,
        `    <changefreq>${changefreq}</changefreq>`,
        `    <priority>${priority}</priority>`,
        "  </url>",
      ].join("\n");
    })
    .join("\n");

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    "<!-- Generated by scripts/generate-sitemap.js — do not hand-edit. -->",
    "<!-- Source of truth: scripts/route-manifest.js + corpus/notes/events data. -->",
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    urls,
    "</urlset>",
    "",
  ].join("\n");
}

const routes = await getSitemapRoutes();

if (routes.length === 0) {
  fail("resolved zero sitemap routes — manifest import likely failed");
}

const contents = buildSitemap(routes);
fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, contents, "utf8");

if (process.exitCode) {
  process.exit();
}

console.log(`Sitemap generated (${routes.length} URLs) -> public/sitemap.xml`);
