const fs = require('fs');

const recordPath = 'src/data/records/FR-AM-0006.js';
let s = fs.readFileSync(recordPath, 'utf8');

const instNeedle = `      vectors: ["partial--timeline-elapsed-without-delivery-genuine-progress-continues"],\n      date: "2025–26",\n    }\n  ],`;
if (!s.includes(instNeedle)) throw new Error('instance insertion anchor not found');
const instReplacement = `      vectors: ["partial--timeline-elapsed-without-delivery-genuine-progress-continues"],\n      date: "2025–26",\n    },\n    {\n      id: "IN-007",\n      qualifiedEvent: "QuantumScape automated pilot-line ramp and milestone-based PowerCo scale-up programme",\n      description: "QuantumScape's 2026 Eagle Line evidence materially advances the manufacturing-scale-up side of the record without satisfying the commercial-viability claim. The company reports that its automated pilot line is producing initial QSE-5 volumes, shipping samples to customers, and achieving greater than 90% uptime on core tools while it works to improve process stability, throughput, quality, and reliability. A July 2026 amendment with Volkswagen's PowerCo restructures the joint programme around milestone-based payments tied to delivery and validation of cells over the following two years. At the same time, QuantumScape's Q2 2026 Form 10-Q continues to describe the company as pre-revenue and explicitly states that commercial success still requires substantial improvements in quality, consistency, reliability, throughput, safety, and cost. This is genuine movement from laboratory demonstration toward repeatable pilot manufacture, but not evidence that solid-state batteries have yet achieved the record's three-threshold conjunction at automotive production scale and commercial cost.",\n      vectors: ["partial--automated-pilot-scale-up-progress-commercial-threshold-unmet"],\n      date: "2026",\n      sources: [\n        {\n          citation: "QuantumScape Corporation, Form 10-Q for the quarter ended June 30, 2026",\n          url: "https://www.sec.gov/Archives/edgar/data/1811414/000119312526316073/qs-20260630.htm",\n          locator: "Product Development; Commercialization and Market Focus",\n        },\n        {\n          citation: "QuantumScape Corporation, Form 8-K, July 16, 2026",\n          url: "https://www.sec.gov/Archives/edgar/data/1811414/000119312526312381/qs-20260716.htm",\n          locator: "Item 1.01 — PowerCo collaboration amendment",\n        },\n        {\n          citation: "QuantumScape, Q2 2026 shareholder letter — Eagle Line Update",\n          url: "https://www.sec.gov/Archives/edgar/data/1811414/000119312526312423/qs-ex99_1.htm",\n          locator: "Eagle Line Update",\n        },\n      ],\n    }\n  ],`;
s = s.replace(instNeedle, instReplacement);

const assessNeedle = `    {\n      id: "AS-002",`;
const assessStart = s.indexOf(assessNeedle);
if (assessStart < 0) throw new Error('AS-002 anchor not found');
const assessEndNeedle = `    }\n  ],\n\n  mechanisms:`;
if (!s.includes(assessEndNeedle)) throw new Error('assessment close anchor not found');
const assessReplacement = `    },\n    {\n      id: "AS-003",\n      date: "2026-08-29",\n      pressureState: "escalating",\n      verificationStage: "VS-03",\n      summary: "IN-007 sustains ESCALATING / VS-03. QuantumScape's automated Eagle Line, customer sample shipments, and milestone-based PowerCo programme are stronger evidence of industrialization than the earlier single-layer and prototype milestones in this record. They directly bear on RM-001 because the work is now testing repeatable manufacturing processes rather than only electrochemical performance. But the same primary filings explicitly preserve the unresolved commercial gap: QuantumScape remains pre-revenue, the line is still a pilot facility, and quality, consistency, reliability, throughput, safety, and cost remain development requirements. No evidence reviewed in this pass demonstrates a production EV battery meeting energy density, safety, and cycle-life requirements simultaneously at commercial manufacturing yield and cost. The attractor therefore remains future operational deployment rather than pilot-line progress.",\n      assessorNote: "Record Review 2026-08-29. Primary evidence: QuantumScape Q2 2026 Form 10-Q; July 16, 2026 Form 8-K covering the PowerCo amendment; Q2 2026 shareholder letter Eagle Line update. Provenance captured directly on IN-007 under PA-004.",\n    }\n  ],\n\n  mechanisms:`;
s = s.replace(assessEndNeedle, assessReplacement);

const mutNeedle = `    // APPEND-ONLY. Newest first.\n    { id: "M-011"`;
if (!s.includes(mutNeedle)) throw new Error('mutation anchor not found');
const mutReplacement = `    // APPEND-ONLY. Newest first.\n    { id: "M-013", date: "2026-08-29", field: "assessment_issued", from: "—", to: "ASSESSMENT-ISSUED", note: "AS-003 issued after bounded FR-AM-0006 Record Review. Pressure state ESCALATING and VS-03 sustained; IN-007 does not meet the commercial-operation attractor." },\n    { id: "M-012", date: "2026-08-29", field: "instance_added", from: "—", to: "IN-007", note: "PA-004 operational provenance trial: QuantumScape automated pilot-line scale-up evidence admitted with canonical sources[] captured at admission." },\n    { id: "M-011"`;
s = s.replace(mutNeedle, mutReplacement);

fs.writeFileSync(recordPath, s);

const doc = `# PA-004 — Provenance-in-Review Operational Trial\n\nStatus: EXECUTED — pending CI / deployment verification\nDate: 2026-08-29\nTrial record: FR-AM-0006 — Solid-State Batteries — Commercial Viability for Electric Vehicles\n\n## Purpose\n\nTest whether structured provenance fits naturally into an ordinary Frontier Record review without turning the review into a provenance-backfill exercise.\n\n## Review result\n\nThe review found one new evidence event worth admission: QuantumScape's 2026 Eagle Line automated pilot-line ramp, customer sample shipments, and the July 2026 PowerCo milestone-based scale-up programme. Primary filings simultaneously confirm that QuantumScape remains pre-revenue and that commercial manufacture still requires improvements in quality, consistency, reliability, throughput, safety, and cost.\n\nIN-007 was therefore admitted as genuine manufacturing-scale-up progress that does not yet satisfy the record's commercial-viability conjunction. AS-003 sustains ESCALATING / VS-03.\n\n## Provenance behaviour tested\n\nIN-007 was authored with sources[] at admission rather than sourced in a second pass. The source material was already open and necessary for the evidence judgment, so the additional provenance work was limited to preserving citation, URL, and useful locator information.\n\n## Opportunistic legacy enrichment\n\nNo legacy instance was enriched in this trial. While reviewing IN-006, an attempted quick provenance reconstruction exposed a possible mismatch between the record's wording about an October 2025 Japanese government production approval and Toyota's readily located official METI certification dated September 2024. Under the pilot boundary, that was not silently converted into provenance or expanded into a historical reconstruction exercise. It is retained as a separate editorial-correction candidate requiring its own bounded verification.\n\nThis is a useful outcome: opportunistic enrichment is permitted only when attribution is readily and confidently established. The pilot did not reward filling sources[] for its own sake.\n\n## Operational finding\n\nPASS at workflow level. Provenance capture for genuinely new evidence was low-friction because the sources were already required for review. The legacy rule also behaved correctly: uncertainty stopped enrichment rather than creating pressure to backfill.\n\n## Boundaries retained\n\n- no corpus-wide provenance backfill;\n- no lowering of the evidence-admission threshold;\n- no source graph, source scoring, extraction metadata, or MCP-specific provenance;\n- no silent correction of a potentially mismatched legacy source claim inside this trial.\n\n## Closure gates\n\nPA-004 closes only after repository validation, build/tests, exact production deployment verification, and confirmation that the public Frontier Record renders IN-007 provenance from the canonical sources[] field.\n`;
fs.writeFileSync('docs/provenance/PA-004-PROVENANCE-IN-REVIEW-TRIAL.md', doc);
